### ISSUE TITLE
Failed to remove dock

### ISSUE THREAD

**Issue by john-heyer** [Jonchun/ubuntu2macOS#4]
Hey, I am also new to linux switching from mac. I ran your script and had two errors in the logs:
```
[ERROR] ubuntu2mac-2020-04-09 17:26:06 | Unable to disable with gnome extension tools... Skipping  ubuntu-dock@ubuntu.com
[ERROR] ubuntu2mac-2020-04-09 17:26:06 | Unable to disable with gnome extension tools... Skipping  dash-to-dock@micxgx.gmail.com
```
I'm not sure if this is exactly why, but the original ubuntu dock was not removed, and the other new macos-like dock (plank?) was hidden behind it. I went through each of the steps manually to figure out where this new dock came from, and how to remove the old dock but I could not figure it out. There was no plank app installed, but I did see the plank-themes directory.
On a whim I just reran your script (receiving a bunch more errors but only because of recloning existing repos), and the same two errors came up in the logs, but this time the new dock was gone, which I've settled with because I don't care too much about the dock anyway.

thanks!

**Comment by jonchun** [comment]
Hmm. What version of Ubuntu did you run this on? Could you attach the entire log?  I don't expect to find anything obvious in there but it could be good to see. If you're not married to stock Ubuntu and would consider KDE Neon (Ubuntu with the latest KDE), check out my macify-linux project which supersedes this one: https://github.com/Jonchun/macify-linux

**Comment by john-heyer** [comment]
[ubuntu2mac.log](https://github.com/Jonchun/ubuntu2macOS/files/4462957/ubuntu2mac.log)

log attached... incudes the logs from multiple runs.

And I'll check that out! Thanks!

Do you use a mac keyboard and mouse? If so, which ones?

**Comment by jonchun** [comment]
I don't use a mac keyboard and mouse. I just use a normal windows mechanic keyboard/gaming mouse since I dual boot. I didn't like it compared to my magic mouse at first, but I got used to it quickly enough.

And what version of Ubuntu were you on? I've only tested this on fresh installs of 18.04 and 20.04 and haven't really tested on anything else.

What is the output of 
`which gnome-shell-extension-tool`
and
`which gnome-extensions`?

The code in this repo was whipped together and I planned on expanding/cleaning it up, but then ended up moving to the macify-linux project instead so there's not very much logging unfortunately. Not quite sure how much effort I want to put into trying to clean up this old stuff to support this to be honest, but let's see if we can figure out your issue at least manually.

**Comment by john-heyer** [comment]
Interesting. The reason I asked is because I too am using a windows mechanical keyboard and although I like that position-wise the keys are now similar to macOS, pressing alt for cmd feels weird.

I am on a fresh install of 18.04. 
which gnome-shell-extension-tool:
`/usr/bin/gnome-shell-extension-tool`
which gnome-extensions is not found.

I completely understand, don't spend much time looking into it, because the dock did go away (although I don't know how or why, and the intended behavior of the script was not the result).

**Comment by jonchun** [comment]
Perhaps if you have a screenshot of what your desktop looks like now it might help me better understand what state you're in. It sounds like you have the old dock back?

Do you see anything in
```
ls -la ~/.config/autostart/
```
I would expect to see a `plank.desktop` file in there. How about running `which plank`?

> I like that position-wise the keys are now similar to macOS, pressing alt for cmd feels weird.

I've always used a windows mech keyboard even when working on my mac (usually I have it hooked up at work to multiple monitors so I have my own peripherals) and don't use apple peripherals anyways. generally I've found that they tend to be form over function.

That being said, I highly recommend you check out my new repo since it sounds like you're on a fresh install of 18.04 anyways. KDE Neon is Ubuntu 18.04 with the latest and greatest KDE software (different desktop environment from Gnome) and basically all the benefits of Ubuntu 18.04 you'll get there as well. Logging is WAY better and I put a lot more time into that one compared to this initial "demo" script. It also gives a much closer mac-like experience. Of course, if you're not liking the cmd key stuff, just disable the kinto parts of the script.

**Comment by john-heyer** [comment]
```
ls -la ~/.config/autostart/
total 12
drwxr-xr-x  2 john john 4096 Apr  9 18:47 .
drwx------ 27 john john 4096 Apr 10 15:28 ..
-rw-r--r--  1 john john  205 Apr  9 18:39 kinto.desktop
```
I believe I removed plank from autostart in the Tweaks app (which I'm not familiar with), in an attempt to remove the other desktop.

Currently:
![image](https://user-images.githubusercontent.com/39138954/79021568-e13e3180-7b49-11ea-9f2d-fa884f6fdc4b.png)

I checked it out and was interested, but you seemed to recommend only running the script in a VM as it sounded not well tested? I also don't want to leave gnome stuff lingering (and perhaps interfering?) from this script.

**Comment by jonchun** [comment]
well, to be fair, this script is even less mature than the other one. That being said, I should probably put a warning on this repo as well.

Yea, if you were to use the other script, it would require that you start fresh with KDE Neon rather than Ubuntu 18.04. Not sure if you're willing to put in that type of time right now, but it's a pretty decent option.

If you're happy with what you're got now, I'd just stick with it.

> the dock did go away 
I think the reason it went away is because you removed/disabled that `plank.desktop` file. It's still installed on your system most likely. If you run `plank` from your Terminal, I bet the second dock will appear.

**Comment by john-heyer** [comment]
Understood. I'll let you know if I test the new setup with Neon. Thanks for the help!
